buildscript {
    repositories {
        google()  // Repositorio de Google para las dependencias de Firebase
        mavenCentral()  // Repositorio Maven Central
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.0'  // Asegúrate de tener la versión correcta del Gradle Plugin
        classpath 'com.google.gms:google-services:4.3.15'  // Dependencia de Google Services (Firebase)
        // Otras dependencias de Gradle si es necesario
    }
}

allprojects {
    repositories {
        google()  // Repositorio de Google
        mavenCentral()  // Repositorio Maven Central
    }
}

rootProject.buildDir = "../build"  // Establece el directorio de construcción

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"  // Configura el directorio de construcción para los subproyectos
}

subprojects {
    project.evaluationDependsOn(":app")  // Configuración adicional para subproyectos
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir  // Tarea para limpiar el proyecto
}
