name: Build and Upload APK

on:
  push:
    branches:
      - master  # Cambia si tu rama principal es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Cambia según la versión que uses

      # 3. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4. Compilar el APK en modo release
      - name: Build APK
        run: flutter build apk --release

      # 5. Subir el APK como artefacto
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # Actualizado a v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
